import {
  Customer,
  SalesPipeline,
  Contract,
  LearningRecord,
  AgentRecord,
  Activity,
  FunnelMetrics,
  RevenueMetrics,
  ChannelMetrics,
} from "@/types/database";

// ===== 顧客マスタデータ =====
export const mockCustomers: (Customer & {
  pipeline?: SalesPipeline;
  contract?: Contract;
  learning?: LearningRecord;
  agent?: AgentRecord;
})[] = [
  {
    id: "c001",
    created_at: "2025-08-25T22:55:16Z",
    updated_at: "2025-08-25T22:55:16Z",
    application_date: "2025-08-25",
    name: "菅生 卓朗",
    email: "takuma.sugo@example.com",
    phone: "090-1234-5678",
    utm_source: "step",
    utm_medium: "header",
    utm_campaign: "30daychuto",
    attribute: "既卒",
    career_history: "一橋大学(2017卒)\n株式会社シーユーシー",
    university: "一橋大学",
    faculty: null,
    graduation_year: 2017,
    sns_accounts: null,
    reference_media: "RemedyのYoutube",
    hobbies: null,
    behavioral_traits: "人とは異なる視点や独創的なアイデアを出すタイプ",
    other_background: null,
    notes: null,
    caution_notes: null,
    priority: "高",
    target_companies: "マッキンゼー、BCG、ベイン、カーニー、S&A、ADL、ローランドベルガー",
    initial_level: "初心者",
    pipeline: {
      id: "p001",
      customer_id: "c001",
      created_at: "2025-08-25T22:55:16Z",
      updated_at: "2025-08-31T00:00:00Z",
      stage: "入金済",
      deal_status: "成約",
      meeting_scheduled_date: "2025-08-28",
      meeting_conducted_date: "2025-08-28",
      meeting_result: "Google Meetで面談",
      agent_interest_at_application: true,
      sales_date: "2025-08-28",
      closing_date: "2025-08-31",
      payment_date: "2025-08-31",
      sales_content: "確実に高く通常契約してくれそう。エージェントは使っている。",
      sales_strategy: "8/31に追加指導、その場で成約したい",
      decision_factor: "スケジュールが合えば入りたいが、時期がない",
      comparison_services: "note",
      second_meeting_category: null,
      postponement_date: null,
      lead_time: null,
      ninety_day_message: null,
      agent_confirmation: null,
      route_by_sales: null,
    },
    contract: {
      id: "ct001",
      customer_id: "c001",
      created_at: "2025-08-31T00:00:00Z",
      updated_at: "2025-08-31T00:00:00Z",
      plan_name: "自社エージェント専用プラン",
      changed_plan: null,
      first_amount: 358400,
      second_amount: null,
      confirmed_amount: 358400,
      discount: 0,
      contract_amount: 358400,
      sales_amount: 358400,
      billing_status: "入金済",
      payment_date: "2025-08-31",
      payment_form_url: null,
      subsidy_eligible: false,
      subsidy_amount: null,
      progress_sheet_url: null,
    },
    learning: {
      id: "l001",
      customer_id: "c001",
      created_at: "2025-08-31T00:00:00Z",
      updated_at: "2025-11-30T00:00:00Z",
      coaching_start_date: "2025-08-31",
      coaching_end_date: "2025-11-30",
      last_coaching_date: "2025-11-29",
      total_sessions: 12,
      assessment_count: 3,
      attendance_rate: 1.0,
      current_level: "中級者",
      latest_evaluation: "勤勉切れ",
      curriculum_progress: 0.9,
      case_interview_progress: "対策を始めたばかりでほぼ初心者",
      case_interview_weaknesses: null,
      completed_sessions: 10,
      mentor_name: "田中",
      contract_months: 3,
      level_fermi: "B",
      level_case: "C+",
      level_mck: "C",
    },
    agent: {
      id: "a001",
      customer_id: "c001",
      created_at: "2025-08-31T00:00:00Z",
      updated_at: "2025-12-01T00:00:00Z",
      agent_service_enrolled: true,
      agent_plan: "一次紹介（自社紹介まだの段階・Stratficatsに）",
      agent_memo: "BCG最終内定を本気で目指しており、他の学習を含めて一気にレベルアップしたいと考えている。",
      job_search_status: "活動中",
      selection_status: "若干笑顔や声の明るさ3月ころ",
      level_up_confirmed: "中級者レベル→中級者レベル",
      document_pass_rate: null,
      exam_count: 0,
      offer_company: null,
      placement_company: null,
      placement_date: null,
      offer_salary: null,
      expected_salary_rate: null,
      referral_fee_rate: 0.33,
      margin: null,
      external_agents: null,
      loss_reason: null,
      loss_detail: null,
    },
  },
  {
    id: "c002",
    created_at: "2025-08-25T22:49:00Z",
    updated_at: "2025-08-25T22:49:00Z",
    application_date: "2025-08-25",
    name: "坂爪 聡",
    email: "shun.hashiz@example.com",
    phone: "080-1335-6596",
    utm_source: "blog",
    utm_medium: "header",
    utm_campaign: null,
    attribute: "既卒",
    career_history: "慶應義塾大学経済学部→日本ロレアル株式会社（ファイナンス・マーケティング職）",
    university: "慶應義塾大学",
    faculty: "経済学部",
    graduation_year: null,
    sns_accounts: "考えるエンジン",
    reference_media: "サウナ・QM検定",
    hobbies: "サウナ・QM検定",
    behavioral_traits: "人とは異なる視点や独創的なアイデアを出すタイプ",
    other_background: "コンコード 2025年10月〜",
    notes: null,
    caution_notes: null,
    priority: null,
    target_companies: "マッキンゼー、BCG、ベイン、カーニー、S&A、ADL",
    initial_level: "初心者",
    pipeline: {
      id: "p002",
      customer_id: "c002",
      created_at: "2025-08-25T22:49:00Z",
      updated_at: "2025-09-01T00:00:00Z",
      stage: "成約",
      deal_status: "成約",
      meeting_scheduled_date: "2025-09-01",
      meeting_conducted_date: "2025-09-01",
      meeting_result: "Google Meetで面談",
      agent_interest_at_application: true,
      sales_date: "2025-09-01",
      closing_date: "2025-09-01",
      payment_date: null,
      sales_content: "他のネットで特急プランを契約できますが、エージェントはコンコード",
      sales_strategy: "追加メンタリング",
      decision_factor: "価格",
      comparison_services: "youtube",
      second_meeting_category: null,
      postponement_date: null,
      lead_time: null,
      ninety_day_message: null,
      agent_confirmation: null,
      route_by_sales: null,
    },
    contract: {
      id: "ct002",
      customer_id: "c002",
      created_at: "2025-09-01T00:00:00Z",
      updated_at: "2025-09-01T00:00:00Z",
      plan_name: "自社エージェント併用プラン",
      changed_plan: null,
      first_amount: null,
      second_amount: null,
      confirmed_amount: null,
      discount: 0,
      contract_amount: null,
      sales_amount: null,
      billing_status: "未請求",
      payment_date: null,
      payment_form_url: null,
      subsidy_eligible: false,
      subsidy_amount: null,
      progress_sheet_url: null,
    },
    learning: {
      id: "l002",
      customer_id: "c002",
      created_at: "2025-11-23T00:00:00Z",
      updated_at: "2025-11-23T00:00:00Z",
      coaching_start_date: "2025-11-23",
      coaching_end_date: "2025-11-23",
      last_coaching_date: "2025-11-23",
      total_sessions: 1,
      assessment_count: 0,
      attendance_rate: null,
      current_level: null,
      latest_evaluation: null,
      curriculum_progress: null,
      case_interview_progress: "初級、書類的なインプットはほぼ6割 考えるエンジン書籍",
      case_interview_weaknesses: null,
      completed_sessions: 1,
      mentor_name: "山本",
      contract_months: 1,
      level_fermi: null,
      level_case: null,
      level_mck: null,
    },
    agent: {
      id: "a002",
      customer_id: "c002",
      created_at: "2025-09-01T00:00:00Z",
      updated_at: "2025-09-01T00:00:00Z",
      agent_service_enrolled: true,
      agent_plan: "コンコード併 → 一次紹介（既に並行の段階/stratficatsに）",
      agent_memo: null,
      job_search_status: "未開始",
      selection_status: null,
      level_up_confirmed: null,
      document_pass_rate: null,
      exam_count: 0,
      offer_company: null,
      placement_company: null,
      placement_date: null,
      offer_salary: null,
      expected_salary_rate: null,
      referral_fee_rate: 0.33,
      margin: null,
      external_agents: "コンコード",
      loss_reason: null,
      loss_detail: null,
    },
  },
  {
    id: "c003",
    created_at: "2025-08-25T17:50:00Z",
    updated_at: "2025-08-25T17:50:00Z",
    application_date: "2025-08-25",
    name: "上條 宗明",
    email: "nananamism@example.com",
    phone: "080-5485-5404",
    utm_source: "blog",
    utm_medium: "header",
    utm_campaign: null,
    attribute: "既卒",
    career_history: "2020.4~2023.3 神奈川県公立高等学校教員\n2023.8~2025.5 Orange Coast College Business Administration\n2025.9~ University of California, Los Angeles (Economics & Finance Major)",
    university: "その他",
    faculty: null,
    graduation_year: null,
    sns_accounts: null,
    reference_media: "特になし",
    hobbies: "長野インターンの経験がある（新卒向け）",
    behavioral_traits: null,
    other_background: null,
    notes: "価格、朝を許容する必要がある",
    caution_notes: null,
    priority: null,
    target_companies: "マッキンゼー、BCG、ベイン、カーニー、総合コンサル(Bgd、アクセンチュア等)",
    initial_level: "初心者",
    pipeline: {
      id: "p003",
      customer_id: "c003",
      created_at: "2025-08-25T17:50:00Z",
      updated_at: "2025-09-16T00:00:00Z",
      stage: "面談実施",
      deal_status: "対応中",
      meeting_scheduled_date: "2025-09-16",
      meeting_conducted_date: "2025-09-16",
      meeting_result: "Facebookインスタグラム",
      agent_interest_at_application: false,
      sales_date: "2025-09-16",
      closing_date: null,
      payment_date: null,
      sales_content: null,
      sales_strategy: null,
      decision_factor: null,
      comparison_services: null,
      second_meeting_category: null,
      postponement_date: null,
      lead_time: "9月",
      ninety_day_message: null,
      agent_confirmation: null,
      route_by_sales: null,
    },
  },
  {
    id: "c004",
    created_at: "2025-08-24T14:28:00Z",
    updated_at: "2025-08-24T14:28:00Z",
    application_date: "2025-08-24",
    name: "森田 優一",
    email: "king_of_yue@example.com",
    phone: "080-1200-5437",
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    attribute: "既卒",
    career_history: "明治大学 法学部\nベイカレント マネージャー",
    university: "明治大学",
    faculty: "法学部",
    graduation_year: null,
    sns_accounts: null,
    reference_media: "リメディのYouTube",
    hobbies: "サッカー",
    behavioral_traits: "チームをまとめたりリーダーシップを取るのが得意",
    other_background: null,
    notes: null,
    caution_notes: null,
    priority: null,
    target_companies: "BCG、S&A",
    initial_level: "中級",
    pipeline: {
      id: "p004",
      customer_id: "c004",
      created_at: "2025-08-24T14:28:00Z",
      updated_at: "2025-09-22T00:00:00Z",
      stage: "入金済",
      deal_status: "成約",
      meeting_scheduled_date: "2025-09-16",
      meeting_conducted_date: "2025-09-16",
      meeting_result: "Facebookインスタグラム",
      agent_interest_at_application: true,
      sales_date: "2025-09-16",
      closing_date: "2025-09-22",
      payment_date: "2025-11-07",
      sales_content: "他のファームも出すが、カリキュラムはblogに特化したものがいいとのこと。",
      sales_strategy: null,
      decision_factor: null,
      comparison_services: "インスタ",
      second_meeting_category: null,
      postponement_date: null,
      lead_time: "9月",
      ninety_day_message: null,
      agent_confirmation: null,
      route_by_sales: null,
    },
    contract: {
      id: "ct004",
      customer_id: "c004",
      created_at: "2025-09-22T00:00:00Z",
      updated_at: "2025-09-22T00:00:00Z",
      plan_name: "自社エージェント専用プラン",
      changed_plan: null,
      first_amount: 120650,
      second_amount: null,
      confirmed_amount: 120650,
      discount: 0,
      contract_amount: 120650,
      sales_amount: 120650,
      billing_status: "入金済",
      payment_date: "2025-11-07",
      payment_form_url: null,
      subsidy_eligible: false,
      subsidy_amount: null,
      progress_sheet_url: null,
    },
    learning: {
      id: "l004",
      customer_id: "c004",
      created_at: "2025-09-22T00:00:00Z",
      updated_at: "2025-11-27T00:00:00Z",
      coaching_start_date: "2025-09-22",
      coaching_end_date: "2025-11-07",
      last_coaching_date: "2025-11-27",
      total_sessions: 4,
      assessment_count: 1.5,
      attendance_rate: 1.0,
      current_level: null,
      latest_evaluation: "勤勉切れ",
      curriculum_progress: 0.6,
      case_interview_progress: "入塾時点ですでに完了 11月中旬",
      case_interview_weaknesses: null,
      completed_sessions: 4,
      mentor_name: "田中",
      contract_months: 2,
      level_fermi: "A",
      level_case: "B+",
      level_mck: "B",
    },
    agent: {
      id: "a004",
      customer_id: "c004",
      created_at: "2025-09-22T00:00:00Z",
      updated_at: "2025-09-22T00:00:00Z",
      agent_service_enrolled: true,
      agent_plan: "blogリファラル(本当にすいません）",
      agent_memo: null,
      job_search_status: "活動中",
      selection_status: "Tier2程、コンペ、60%",
      level_up_confirmed: null,
      document_pass_rate: null,
      exam_count: 0,
      offer_company: null,
      placement_company: null,
      placement_date: null,
      offer_salary: null,
      expected_salary_rate: null,
      referral_fee_rate: 0.33,
      margin: null,
      external_agents: null,
      loss_reason: null,
      loss_detail: null,
    },
  },
  {
    id: "c005",
    created_at: "2025-08-23T13:40:50Z",
    updated_at: "2025-08-23T13:40:50Z",
    application_date: "2025-08-23",
    name: "長 洋騎",
    email: "banpocorg@example.com",
    phone: "080-5843-3122",
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    attribute: "新卒",
    career_history: "東京大学",
    university: "東京大学",
    faculty: null,
    graduation_year: null,
    sns_accounts: null,
    reference_media: "なし",
    hobbies: "なし、バスケ、旅・人と話すなど、人とは異なる視点や独創的なアイデアを出すタイプ",
    behavioral_traits: null,
    other_background: "未定マッチングプレマッチングPSGテスト。もっと色合い欲しいなら直接聞かれると心配です。",
    notes: null,
    caution_notes: null,
    priority: null,
    target_companies: "マッキンゼー、マッキンゼーへの紹介（自社紹介まだ（Stratficatsに））",
    initial_level: "初心者",
    pipeline: {
      id: "p005",
      customer_id: "c005",
      created_at: "2025-08-23T13:40:50Z",
      updated_at: "2025-09-24T00:00:00Z",
      stage: "面談実施",
      deal_status: "対応中",
      meeting_scheduled_date: "2025-09-23",
      meeting_conducted_date: "2025-09-24",
      meeting_result: null,
      agent_interest_at_application: false,
      sales_date: "2025-09-24",
      closing_date: null,
      payment_date: null,
      sales_content: "あまりにも価格が高いとのこと",
      sales_strategy: "リマインド",
      decision_factor: null,
      comparison_services: "Google検索、note",
      second_meeting_category: null,
      postponement_date: null,
      lead_time: null,
      ninety_day_message: null,
      agent_confirmation: "なし",
      route_by_sales: null,
    },
  },
  {
    id: "c006",
    created_at: "2025-08-22T06:10:00Z",
    updated_at: "2025-08-22T06:10:00Z",
    application_date: "2025-08-22",
    name: "佐瀬 礼人",
    email: "ayats.sato@example.com",
    phone: "090-3811-9801",
    utm_source: "blog",
    utm_medium: "header",
    utm_campaign: null,
    attribute: "既卒",
    career_history: "~2019年11月（大学3年時）に公認会計士試験合格。\n~2020年2月に有限責任監査法人トーマツ金融事業部に入社\n~2021年3月に早稲田大学社会科学部卒業\n~2022年12月までトーマツにて金融機関の会計監査業務に従事\n~2023年1月に株式会社国際協力銀行入社\n~2024年8月まで欧州企業向けのグリーンファイナンスを規制側から\n~2024年8月から同社イスタンプール駐在商事務所",
    university: "早稲田大学",
    faculty: "社会科学部",
    graduation_year: 2021,
    sns_accounts: null,
    reference_media: null,
    hobbies: "映画鑑賞、旅行",
    behavioral_traits: "知識や経歴には自信がないが、思考力や思考スピードに特に集中する",
    other_background: "2025年末にMcK入社を志望",
    notes: null,
    caution_notes: null,
    priority: null,
    target_companies: "マッキンゼー、BCG",
    initial_level: "初心者",
    pipeline: {
      id: "p006",
      customer_id: "c006",
      created_at: "2025-08-22T06:10:00Z",
      updated_at: "2025-08-24T00:00:00Z",
      stage: "成約",
      deal_status: "成約",
      meeting_scheduled_date: "2025-08-24",
      meeting_conducted_date: "2025-08-24",
      meeting_result: "Google Meetで面談",
      agent_interest_at_application: false,
      sales_date: "2025-08-24",
      closing_date: "2025-08-24",
      payment_date: null,
      sales_content: "ケースのスタンダリングは継続いただきたい",
      sales_strategy: null,
      decision_factor: "その他",
      comparison_services: null,
      second_meeting_category: null,
      postponement_date: null,
      lead_time: null,
      ninety_day_message: null,
      agent_confirmation: null,
      route_by_sales: null,
    },
    contract: {
      id: "ct006",
      customer_id: "c006",
      created_at: "2025-08-24T00:00:00Z",
      updated_at: "2025-08-24T00:00:00Z",
      plan_name: "自社エージェント併用プラン",
      changed_plan: null,
      first_amount: 358400,
      second_amount: null,
      confirmed_amount: 358400,
      discount: 0,
      contract_amount: 358400,
      sales_amount: 358400,
      billing_status: "入金済",
      payment_date: "2025-08-24",
      payment_form_url: null,
      subsidy_eligible: false,
      subsidy_amount: null,
      progress_sheet_url: null,
    },
  },
  {
    id: "c007",
    created_at: "2025-08-22T02:59:00Z",
    updated_at: "2025-08-22T02:59:00Z",
    application_date: "2025-08-22",
    name: "堀江 明良",
    email: "yukihona200@example.com",
    phone: "080-9269-5400",
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    attribute: "既卒",
    career_history: "慶應義塾大学総合政策学部\nNTTドコモ入社\nNTTドコモビジネス(旧NTTコミュニケーションズ)\ndsn\nジェネレーティブAIタスクフォースにて、法人のお客様に生成AI導入のコンサルティングとプリセールス業務に従事",
    university: "慶應義塾大学",
    faculty: "総合政策学部",
    graduation_year: null,
    sns_accounts: null,
    reference_media: null,
    hobbies: null,
    behavioral_traits: null,
    other_background: null,
    notes: "価格、他サービスと比較している、それをもう1度確認する意向（約）",
    caution_notes: null,
    priority: null,
    target_companies: "マッキンゼー、BCG、ベイン",
    initial_level: null,
    pipeline: {
      id: "p007",
      customer_id: "c007",
      created_at: "2025-08-22T02:59:00Z",
      updated_at: "2025-08-26T00:00:00Z",
      stage: "面談実施",
      deal_status: "対応中",
      meeting_scheduled_date: "2025-08-26",
      meeting_conducted_date: "2025-08-26",
      meeting_result: "Google Meetで面談",
      agent_interest_at_application: false,
      sales_date: "2025-08-26",
      closing_date: null,
      payment_date: null,
      sales_content: "出前感起きっぽく、明確な反応は薄かった。FBに対しても山さんの質問の意図がわからなくなった。と指摘された。ただしサービスには関心がありの心の灯りがあり、追加メンタリングは管理ということだった。ただのディケアかもしれないが...",
      sales_strategy: "追加指導、メンタリングのクオリティを納得してもらう",
      decision_factor: null,
      comparison_services: "Prism",
      second_meeting_category: "自拉",
      postponement_date: null,
      lead_time: null,
      ninety_day_message: null,
      agent_confirmation: null,
      route_by_sales: null,
    },
  },
  {
    id: "c008",
    created_at: "2025-08-21T01:56:00Z",
    updated_at: "2025-08-21T01:56:00Z",
    application_date: "2025-08-21",
    name: "新堂 慶",
    email: "op1414210@example.com",
    phone: "080-4121-1993",
    utm_source: "blog",
    utm_medium: "header",
    utm_campaign: null,
    attribute: "既卒",
    career_history: "2014年4月〜2016年3月 早稲田大学 政治経済学部 卒業\n2016年4月〜2022年3月 ヤマハ発動機 株式会社 営業部門/事業戦略部門/新事業開発、サプライチェーン戦略\n2022年4月〜現在 デロイト トーマツ コンサルティング合同会社 ERP導入支援/販売・購買・在庫の業務改善",
    university: "早稲田大学",
    faculty: "政治経済学部",
    graduation_year: 2016,
    sns_accounts: null,
    reference_media: null,
    hobbies: "映画鑑賞、旅行",
    behavioral_traits: "知識や経歴には自信がないが、思考力や思考スピードに特に集中する",
    other_background: null,
    notes: null,
    caution_notes: null,
    priority: null,
    target_companies: "マッキンゼー、BCG",
    initial_level: "初級",
    pipeline: {
      id: "p008",
      customer_id: "c008",
      created_at: "2025-08-21T01:56:00Z",
      updated_at: "2025-08-27T00:00:00Z",
      stage: "入金済",
      deal_status: "成約",
      meeting_scheduled_date: "2025-08-27",
      meeting_conducted_date: "2025-08-27",
      meeting_result: "Google Meetで面談",
      agent_interest_at_application: false,
      sales_date: "2025-08-27",
      closing_date: "2025-08-27",
      payment_date: "2025-08-27",
      sales_content: "斡旋プランにはBCGBダイレクトリクルートを入れたいスキーム。",
      sales_strategy: null,
      decision_factor: "その他",
      comparison_services: null,
      second_meeting_category: null,
      postponement_date: null,
      lead_time: null,
      ninety_day_message: null,
      agent_confirmation: null,
      route_by_sales: null,
    },
    contract: {
      id: "ct008",
      customer_id: "c008",
      created_at: "2025-08-27T00:00:00Z",
      updated_at: "2025-08-27T00:00:00Z",
      plan_name: "自社エージェント併用プラン",
      changed_plan: "既卒エージェント併用プラン抜差額BCG/Bain",
      first_amount: 373500,
      second_amount: null,
      confirmed_amount: 373500,
      discount: 0,
      contract_amount: 373500,
      sales_amount: 373500,
      billing_status: "入金済",
      payment_date: "2025-08-27",
      payment_form_url: null,
      subsidy_eligible: false,
      subsidy_amount: null,
      progress_sheet_url: null,
    },
    learning: {
      id: "l008",
      customer_id: "c008",
      created_at: "2025-09-03T00:00:00Z",
      updated_at: "2025-12-05T00:00:00Z",
      coaching_start_date: "2025-09-03",
      coaching_end_date: "2025-12-03",
      last_coaching_date: "2025-12-05",
      total_sessions: 12,
      assessment_count: 3,
      attendance_rate: 1.0,
      current_level: "中級者",
      latest_evaluation: "勤勉切れ",
      curriculum_progress: 0.9,
      case_interview_progress: "初級、書類的なインプットはほぼ6割。読んだ（読んでいる、読む予定を含む）書籍",
      case_interview_weaknesses: "1. 回答が制限的になってしまう\nフレームワークの使い方が正しく\n\n2. 日本語が若干怪しい\n論理関係で状況を整のなかでは限",
      completed_sessions: 9,
      mentor_name: "山本",
      contract_months: 3,
      level_fermi: "B+",
      level_case: "B",
      level_mck: "C+",
    },
    agent: {
      id: "a008",
      customer_id: "c008",
      created_at: "2025-09-03T00:00:00Z",
      updated_at: "2025-12-05T00:00:00Z",
      agent_service_enrolled: true,
      agent_plan: "一次紹介（既に並行の段階/stratficatsに）",
      agent_memo: "特定のエージェントとの付き合いはないが、ダイレクトリクルーティングを中心に活動されているとのこと。BCGはもう仕方がないが、ベインなどまだ応募していないのでそちらは当社で行きたい。",
      job_search_status: "活動中",
      selection_status: "書面にディスカッション 12月ころ",
      level_up_confirmed: "中級者レベル→中級者レベル",
      document_pass_rate: null,
      exam_count: 0,
      offer_company: null,
      placement_company: null,
      placement_date: null,
      offer_salary: null,
      expected_salary_rate: null,
      referral_fee_rate: 0.33,
      margin: null,
      external_agents: null,
      loss_reason: null,
      loss_detail: null,
    },
  },
  {
    id: "c009",
    created_at: "2025-08-20T07:16:00Z",
    updated_at: "2025-08-20T07:16:00Z",
    application_date: "2025-08-20",
    name: "猫田 大博",
    email: "hiroki.nek@example.com",
    phone: "080-3027-6810",
    utm_source: "x",
    utm_medium: "profile",
    utm_campaign: null,
    attribute: "既卒",
    career_history: "信州大学工学先進理工研究/電気情報連携構造分野",
    university: "信州大学",
    faculty: "工学先進理工研究",
    graduation_year: null,
    sns_accounts: null,
    reference_media: null,
    hobbies: null,
    behavioral_traits: null,
    other_background: "29卒大学院で修士号を取りに来た。これから本格的に始めるかその前に",
    notes: "他サービスと比較している",
    caution_notes: null,
    priority: null,
    target_companies: null,
    initial_level: null,
    pipeline: {
      id: "p009",
      customer_id: "c009",
      created_at: "2025-08-20T07:16:00Z",
      updated_at: "2025-10-01T00:00:00Z",
      stage: "面談実施",
      deal_status: "対応中",
      meeting_scheduled_date: "2025-09-22",
      meeting_conducted_date: "2025-10-01",
      meeting_result: null,
      agent_interest_at_application: false,
      sales_date: "2025-10-01",
      closing_date: null,
      payment_date: null,
      sales_content: null,
      sales_strategy: null,
      decision_factor: null,
      comparison_services: null,
      second_meeting_category: null,
      postponement_date: null,
      lead_time: null,
      ninety_day_message: null,
      agent_confirmation: null,
      route_by_sales: null,
    },
  },
  {
    id: "c010",
    created_at: "2025-08-20T01:44:00Z",
    updated_at: "2025-08-20T01:44:00Z",
    application_date: "2025-08-20",
    name: "中山 孝一郎",
    email: "kaichiro.n@example.com",
    phone: "090-9115-6407",
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    attribute: "新卒",
    career_history: "経済学部、東京大学 経済学部 経済学科\n職歴 26卒、KPMG FA/M株式会社またはPwCアドバイザリー合同会社にて入社予定\n入社先は決めていない",
    university: "東京大学",
    faculty: "経済学部",
    graduation_year: null,
    sns_accounts: "XのアカウントKA、Prism",
    reference_media: null,
    hobbies: "趣味：筋トレ 特性：確認語",
    behavioral_traits: "現時点では戦略フ",
    other_background: "中国で外資戦略ファームに入りたい\n関き始めてから時期が取れるのか？\n\nBCG、bainに二次面接者があった\nマスターコースたとれた上級、思考力で変えられる\nprism+塾入メンタリングで対策をしている\n中のエージェントと話す機会がある",
    notes: "価格、他サービスと比較している",
    caution_notes: null,
    priority: null,
    target_companies: "BCG、ベイン、カーニー、S&A、ADL、ローランドベルガー、その他戦略コンサル",
    initial_level: null,
    pipeline: {
      id: "p010",
      customer_id: "c010",
      created_at: "2025-08-20T01:44:00Z",
      updated_at: "2025-09-12T00:00:00Z",
      stage: "面談実施",
      deal_status: "対応中",
      meeting_scheduled_date: "2025-08-27",
      meeting_conducted_date: "2025-09-12",
      meeting_result: null,
      agent_interest_at_application: false,
      sales_date: "2025-09-12",
      closing_date: null,
      payment_date: null,
      sales_content: "まだ大学生だが、社会人2年目以降通過に転職を検討している。入社後は上記で検討してれている。考えるエンジン講座と比較して検討",
      sales_strategy: "上記で検討してれている。考えるエンジンの会に長セミナーを紹介すると、自社の質が良さそうという印象。導かれてStrategistsも思い出した。",
      decision_factor: null,
      comparison_services: "Xで知っていた、エージェントの会に長セミナー/考えるエンジン",
      second_meeting_category: "自拉",
      postponement_date: null,
      lead_time: null,
      ninety_day_message: null,
      agent_confirmation: null,
      route_by_sales: null,
    },
  },
];

// ===== 活動履歴 =====
export const mockActivities: Activity[] = [
  {
    id: "act001",
    customer_id: "c001",
    created_at: "2025-08-28T10:00:00Z",
    activity_type: "面談",
    content: "初回面談実施。Google Meetにて。戦略コンサル転職に強い意欲。BCG最終内定を本気で目指している。",
    created_by: "山本",
  },
  {
    id: "act002",
    customer_id: "c001",
    created_at: "2025-08-31T14:00:00Z",
    activity_type: "ステータス変更",
    content: "成約。自社エージェント専用プラン、¥358,400で契約。即日入金。",
    created_by: "山本",
  },
  {
    id: "act003",
    customer_id: "c002",
    created_at: "2025-09-01T11:00:00Z",
    activity_type: "面談",
    content: "初回面談。他ネットで特急プランを契約検討中だが、エージェントはコンコードを検討中。",
    created_by: "山本",
  },
  {
    id: "act004",
    customer_id: "c004",
    created_at: "2025-09-16T15:00:00Z",
    activity_type: "面談",
    content: "面談実施。カリキュラムはblogに特化したものを希望。他ファームへの出願も視野。",
    created_by: "山本",
  },
  {
    id: "act005",
    customer_id: "c008",
    created_at: "2025-08-27T09:00:00Z",
    activity_type: "面談",
    content: "面談実施。BCGダイレクトリクルーティング中心で活動中。当社でベインなどに応募希望。",
    created_by: "山本",
  },
  {
    id: "act006",
    customer_id: "c008",
    created_at: "2025-08-27T16:00:00Z",
    activity_type: "ステータス変更",
    content: "成約。自社エージェント併用プラン、¥373,500で契約。即日入金。",
    created_by: "山本",
  },
];

// ===== ファネルメトリクス (P/Lシートベース) =====
export const mockFunnelMetrics: FunnelMetrics[] = [
  { period: "2025/05", applications: 17, scheduled: 11, conducted: 11, closed: 3, scheduling_rate: 0.65, conduct_rate: 1.0, closing_rate: 0.27 },
  { period: "2025/06", applications: 36, scheduled: 29, conducted: 21, closed: 8, scheduling_rate: 0.81, conduct_rate: 0.72, closing_rate: 0.38 },
  { period: "2025/07", applications: 40, scheduled: 35, conducted: 27, closed: 9, scheduling_rate: 0.88, conduct_rate: 0.77, closing_rate: 0.33 },
  { period: "2025/08", applications: 24, scheduled: 20, conducted: 19, closed: 10, scheduling_rate: 0.83, conduct_rate: 0.95, closing_rate: 0.53 },
  { period: "2025/09", applications: 29, scheduled: 23, conducted: 22, closed: 9, scheduling_rate: 0.79, conduct_rate: 0.96, closing_rate: 0.41 },
  { period: "2025/10", applications: 35, scheduled: 28, conducted: 24, closed: 12, scheduling_rate: 0.80, conduct_rate: 0.86, closing_rate: 0.50 },
  { period: "2025/11", applications: 38, scheduled: 28, conducted: 20, closed: 10, scheduling_rate: 0.74, conduct_rate: 0.71, closing_rate: 0.50 },
  { period: "2025/12", applications: 20, scheduled: 18, conducted: 16, closed: 9, scheduling_rate: 0.90, conduct_rate: 0.89, closing_rate: 0.56 },
  { period: "2026/01", applications: 23, scheduled: 20, conducted: 16, closed: 11, scheduling_rate: 0.87, conduct_rate: 0.80, closing_rate: 0.69 },
  { period: "2026/02", applications: 29, scheduled: 25, conducted: 15, closed: 7, scheduling_rate: 0.86, conduct_rate: 0.60, closing_rate: 0.47 },
];

// ===== 売上メトリクス =====
export const mockRevenueMetrics: RevenueMetrics[] = [
  { period: "2025/05", confirmed_revenue: 2330604, projected_revenue: 3200000, school_revenue: 1800000, agent_revenue: 0, content_revenue: 130604, other_revenue: 400000 },
  { period: "2025/06", confirmed_revenue: 4500000, projected_revenue: 5800000, school_revenue: 3200000, agent_revenue: 500000, content_revenue: 300000, other_revenue: 500000 },
  { period: "2025/07", confirmed_revenue: 5200000, projected_revenue: 7100000, school_revenue: 3800000, agent_revenue: 600000, content_revenue: 300000, other_revenue: 500000 },
  { period: "2025/08", confirmed_revenue: 6800000, projected_revenue: 8500000, school_revenue: 4500000, agent_revenue: 1200000, content_revenue: 400000, other_revenue: 700000 },
  { period: "2025/09", confirmed_revenue: 7200000, projected_revenue: 9200000, school_revenue: 4800000, agent_revenue: 1400000, content_revenue: 350000, other_revenue: 650000 },
  { period: "2025/10", confirmed_revenue: 8100000, projected_revenue: 10500000, school_revenue: 5500000, agent_revenue: 1600000, content_revenue: 400000, other_revenue: 600000 },
  { period: "2025/11", confirmed_revenue: 8500000, projected_revenue: 11000000, school_revenue: 5800000, agent_revenue: 1700000, content_revenue: 350000, other_revenue: 650000 },
  { period: "2025/12", confirmed_revenue: 9200000, projected_revenue: 11400000, school_revenue: 6200000, agent_revenue: 1800000, content_revenue: 400000, other_revenue: 800000 },
  { period: "2026/01", confirmed_revenue: 9800000, projected_revenue: 12000000, school_revenue: 6500000, agent_revenue: 2100000, content_revenue: 450000, other_revenue: 750000 },
  { period: "2026/02", confirmed_revenue: 10200000, projected_revenue: 12800000, school_revenue: 6800000, agent_revenue: 2200000, content_revenue: 500000, other_revenue: 700000 },
];

// ===== チャネル別メトリクス =====
export const mockChannelMetrics: ChannelMetrics[] = [
  { channel: "SEO(直LP)", applications: 103, closings: 42, revenue: 15000000, cpa: 0, ltv: 357000 },
  { channel: "SEO(Blog)", applications: 32, closings: 14, revenue: 5200000, cpa: 0, ltv: 371000 },
  { channel: "X", applications: 10, closings: 4, revenue: 1400000, cpa: 0, ltv: 350000 },
  { channel: "Youtube", applications: 27, closings: 11, revenue: 4500000, cpa: 0, ltv: 409000 },
  { channel: "コンサルタイムズ", applications: 8, closings: 3, revenue: 1100000, cpa: 0, ltv: 367000 },
  { channel: "有料note", applications: 10, closings: 5, revenue: 2000000, cpa: 0, ltv: 400000 },
  { channel: "アフィリエイト", applications: 7, closings: 2, revenue: 800000, cpa: 15000, ltv: 400000 },
  { channel: "口コミ・紹介", applications: 5, closings: 3, revenue: 1200000, cpa: 0, ltv: 400000 },
  { channel: "Google広告", applications: 15, closings: 5, revenue: 2000000, cpa: 28000, ltv: 400000 },
  { channel: "FB広告", applications: 8, closings: 2, revenue: 700000, cpa: 35000, ltv: 350000 },
];
