import type { Course, Module, Lesson, Enrollment, Assignment, ProgressSheet, Announcement, EnrollmentApplication } from "@strategy-school/shared-db";

export const mockCourses: Course[] = [
  {
    id: "course-1",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    title: "ケース面接基礎講座",
    slug: "case-interview-basics",
    description: "戦略コンサルティングファームのケース面接に必要な基礎スキルを体系的に学ぶコースです。フレームワーク思考、構造化、数値推定の基本を網羅します。",
    category: "ケース面接",
    level: "beginner",
    target_attribute: null,
    total_lessons: 12,
    duration_weeks: 8,
    is_active: true,
    sort_order: 1,
    status: "published",
    thumbnail_url: null,
  },
  {
    id: "course-2",
    created_at: "2025-01-15T00:00:00Z",
    updated_at: "2025-01-15T00:00:00Z",
    title: "ケース面接実践演習",
    slug: "case-interview-practice",
    description: "実際のケース問題を使った演習中心のコース。BCG・マッキンゼーの出題傾向を分析し、本番さながらの練習を行います。",
    category: "ケース面接",
    level: "intermediate",
    target_attribute: null,
    total_lessons: 10,
    duration_weeks: 10,
    is_active: true,
    sort_order: 2,
    status: "published",
    thumbnail_url: null,
  },
  {
    id: "course-3",
    created_at: "2025-02-01T00:00:00Z",
    updated_at: "2025-02-01T00:00:00Z",
    title: "ビヘイビア面接対策",
    slug: "behavioral-interview",
    description: "戦略ファーム特有のビヘイビア面接（Fit Interview）への対策コース。自己紹介、Why Consulting、リーダーシップ経験の伝え方を学びます。",
    category: "ビヘイビア面接",
    level: "beginner",
    target_attribute: null,
    total_lessons: 8,
    duration_weeks: 6,
    is_active: true,
    sort_order: 3,
    status: "published",
    thumbnail_url: null,
  },
  {
    id: "course-4",
    created_at: "2025-02-15T00:00:00Z",
    updated_at: "2025-02-15T00:00:00Z",
    title: "戦略思考フレームワーク",
    slug: "strategy-frameworks",
    description: "MECE、仮説思考、Issue Tree など、戦略コンサルタントが日常的に使うフレームワークを実践的に学びます。",
    category: "戦略思考",
    level: "intermediate",
    target_attribute: null,
    total_lessons: 15,
    duration_weeks: 12,
    is_active: true,
    sort_order: 4,
    status: "published",
    thumbnail_url: null,
  },
  {
    id: "course-5",
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2025-03-01T00:00:00Z",
    title: "書類選考突破講座",
    slug: "resume-preparation",
    description: "戦略ファーム向けの職務経歴書・カバーレターの書き方を指導。通過率を高めるためのポイントを徹底解説。",
    category: "書類対策",
    level: "beginner",
    target_attribute: "既卒",
    total_lessons: 6,
    duration_weeks: 4,
    is_active: true,
    sort_order: 5,
    status: "published",
    thumbnail_url: null,
  },
];

export const mockModules: (Module & { lessons: Lesson[] })[] = [
  {
    id: "mod-1",
    course_id: "course-1",
    title: "第1章: ケース面接とは",
    sort_order: 1,
    lessons: [
      {
        id: "lesson-1-1",
        course_id: "course-1",
        created_at: "2025-01-01T00:00:00Z",
        updated_at: "2025-01-01T00:00:00Z",
        title: "ケース面接の概要と評価ポイント",
        description: "ケース面接とは何か、面接官は何を見ているのかを解説します。",
        lesson_type: "動画",
        content_url: null,
        video_url: null,
        markdown_content: null,
        copy_protected: false,
        duration_minutes: 30,
        sort_order: 1,
        is_active: true,
      },
      {
        id: "lesson-1-2",
        course_id: "course-1",
        created_at: "2025-01-01T00:00:00Z",
        updated_at: "2025-01-01T00:00:00Z",
        title: "各ファームの出題傾向",
        description: "BCG、マッキンゼー、ベインなど主要ファームの特徴を比較します。",
        lesson_type: "テキスト",
        content_url: null,
        video_url: null,
        markdown_content: "<h2>主要戦略ファームの出題傾向</h2><p>各ファームには独自の面接スタイルがあります...</p>",
        copy_protected: true,
        duration_minutes: 20,
        sort_order: 2,
        is_active: true,
      },
    ],
  },
  {
    id: "mod-2",
    course_id: "course-1",
    title: "第2章: フレームワーク思考",
    sort_order: 2,
    lessons: [
      {
        id: "lesson-2-1",
        course_id: "course-1",
        created_at: "2025-01-01T00:00:00Z",
        updated_at: "2025-01-01T00:00:00Z",
        title: "MECE と Issue Tree",
        description: "問題を構造化するための基本ツールを学びます。",
        lesson_type: "動画",
        content_url: null,
        video_url: null,
        markdown_content: null,
        copy_protected: false,
        duration_minutes: 45,
        sort_order: 1,
        is_active: true,
      },
      {
        id: "lesson-2-2",
        course_id: "course-1",
        created_at: "2025-01-01T00:00:00Z",
        updated_at: "2025-01-01T00:00:00Z",
        title: "フレームワーク演習問題",
        description: "実際のケースを使ってフレームワークを適用する練習です。",
        lesson_type: "ケース演習",
        content_url: null,
        video_url: null,
        markdown_content: null,
        copy_protected: false,
        duration_minutes: 60,
        sort_order: 2,
        is_active: true,
      },
    ],
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: "enroll-1",
    user_id: "mock-student",
    course_id: "course-1",
    status: "active",
    enrolled_at: "2025-02-01T00:00:00Z",
    deadline: "2025-04-01T00:00:00Z",
    schedule_status: "on_track",
  },
  {
    id: "enroll-2",
    user_id: "mock-student",
    course_id: "course-3",
    status: "active",
    enrolled_at: "2025-02-15T00:00:00Z",
    deadline: "2025-04-15T00:00:00Z",
    schedule_status: "slightly_behind",
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    title: "3月のメンタリングスケジュール更新",
    content: "3月のメンタリングスケジュールが更新されました。各自のダッシュボードからご確認ください。予約枠に限りがありますので、お早めにご予約をお願いします。",
    priority: "normal",
    published_at: "2025-02-25T10:00:00Z",
    author_id: "admin-1",
  },
  {
    id: "ann-2",
    title: "新コース「戦略思考フレームワーク」リリース",
    content: "お待たせしました！新コース「戦略思考フレームワーク」がリリースされました。MECE、仮説思考、Issue Treeなど、実践的なフレームワークを12週間で習得できます。",
    priority: "high",
    published_at: "2025-02-20T09:00:00Z",
    author_id: "admin-1",
  },
  {
    id: "ann-3",
    title: "システムメンテナンスのお知らせ",
    content: "2月28日 深夜2:00〜4:00にシステムメンテナンスを実施します。この間、一部機能がご利用いただけません。ご迷惑をおかけしますが、ご了承ください。",
    priority: "urgent",
    published_at: "2025-02-18T14:00:00Z",
    author_id: "admin-1",
  },
];

export const mockApplications: EnrollmentApplication[] = [
  {
    id: "app-1",
    name: "田中 太郎",
    email: "tanaka@example.com",
    phone: "090-1234-5678",
    motivation: "BCGへの転職を目指しています。ケース面接の対策を体系的に行いたいと考えています。",
    experience: "総合商社3年目。M&A関連業務に従事。",
    course_id: "course-1",
    status: "pending",
    created_at: "2025-02-26T10:00:00Z",
  },
  {
    id: "app-2",
    name: "佐藤 花子",
    email: "sato@example.com",
    phone: "080-9876-5432",
    motivation: "マッキンゼーに興味があり、戦略思考を鍛えたいです。",
    experience: "外資系メーカー マーケティング部門 2年。",
    course_id: "course-4",
    status: "approved",
    created_at: "2025-02-20T08:00:00Z",
    reviewed_at: "2025-02-21T10:00:00Z",
  },
];

export const mockProgressSheets: ProgressSheet[] = [
  {
    id: "ps-1",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2025-02-20",
    session_number: 1,
    understanding: 3,
    effort: 4,
    progress: 3,
    communication: 4,
    overall_rating: 3,
    feedback: "基礎的なフレームワークの理解は良好です。次回からは実践的な演習に入りましょう。",
    strengths: "論理的思考力が高い。構造化が得意。",
    improvements: "数値推定のスピードを上げる必要あり。",
    next_goals: "フェルミ推定の練習を5問以上行う。",
  },
  {
    id: "ps-2",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2025-02-27",
    session_number: 2,
    understanding: 4,
    effort: 4,
    progress: 4,
    communication: 4,
    overall_rating: 4,
    feedback: "前回からの改善が見られます。フェルミ推定のスピードが向上しました。",
    strengths: "改善意欲が高い。宿題をしっかりこなしている。",
    improvements: "ケース面接での時間配分を意識する。",
    next_goals: "30分のケース面接を3回模擬実施する。",
  },
];
