import type { Course, Module, Lesson, Enrollment, Assignment, ProgressSheet, Announcement, EnrollmentApplication } from "@strategy-school/shared-db";

export const mockCourses: Course[] = [
  {
    id: "course-1",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    title: "ケース面接基礎講座",
    slug: "case-interview-basics",
    description: "戦略コンサルティングファームのケース面接に必要な基礎スキルを体系的に学ぶコースです。フレームワーク思考、構造化、数値推定の基本を網羅します。",
    category: "ケース面接",
    level: "beginner",
    target_attribute: null,
    total_lessons: 12,
    duration_weeks: 8,
    is_active: true,
    sort_order: 1,
    status: "published",
    thumbnail_url: null,
  },
  {
    id: "course-2",
    created_at: "2025-01-15T00:00:00Z",
    updated_at: "2025-01-15T00:00:00Z",
    title: "ケース面接実践演習",
    slug: "case-interview-practice",
    description: "実際のケース問題を使った演習中心のコース。BCG・マッキンゼーの出題傾向を分析し、本番さながらの練習を行います。",
    category: "ケース面接",
    level: "intermediate",
    target_attribute: null,
    total_lessons: 10,
    duration_weeks: 10,
    is_active: true,
    sort_order: 2,
    status: "published",
    thumbnail_url: null,
  },
  {
    id: "course-3",
    created_at: "2025-02-01T00:00:00Z",
    updated_at: "2025-02-01T00:00:00Z",
    title: "ビヘイビア面接対策",
    slug: "behavioral-interview",
    description: "戦略ファーム特有のビヘイビア面接（Fit Interview）への対策コース。自己紹介、Why Consulting、リーダーシップ経験の伝え方を学びます。",
    category: "ビヘイビア面接",
    level: "beginner",
    target_attribute: null,
    total_lessons: 8,
    duration_weeks: 6,
    is_active: true,
    sort_order: 3,
    status: "published",
    thumbnail_url: null,
  },
  {
    id: "course-4",
    created_at: "2025-02-15T00:00:00Z",
    updated_at: "2025-02-15T00:00:00Z",
    title: "戦略思考フレームワーク",
    slug: "strategy-frameworks",
    description: "MECE、仮説思考、Issue Tree など、戦略コンサルタントが日常的に使うフレームワークを実践的に学びます。",
    category: "戦略思考",
    level: "intermediate",
    target_attribute: null,
    total_lessons: 15,
    duration_weeks: 12,
    is_active: true,
    sort_order: 4,
    status: "published",
    thumbnail_url: null,
  },
  {
    id: "course-5",
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2025-03-01T00:00:00Z",
    title: "書類選考突破講座",
    slug: "resume-preparation",
    description: "戦略ファーム向けの職務経歴書・カバーレターの書き方を指導。通過率を高めるためのポイントを徹底解説。",
    category: "書類対策",
    level: "beginner",
    target_attribute: "既卒",
    total_lessons: 6,
    duration_weeks: 4,
    is_active: true,
    sort_order: 5,
    status: "published",
    thumbnail_url: null,
  },
];

export const mockModules: (Module & { lessons: Lesson[] })[] = [
  {
    id: "mod-1",
    course_id: "course-1",
    title: "第1章: ケース面接とは",
    sort_order: 1,
    lessons: [
      {
        id: "lesson-1-1",
        course_id: "course-1",
        created_at: "2025-01-01T00:00:00Z",
        updated_at: "2025-01-01T00:00:00Z",
        title: "ケース面接の概要と評価ポイント",
        description: "ケース面接とは何か、面接官は何を見ているのかを解説します。",
        lesson_type: "動画",
        content_url: null,
        video_url: null,
        markdown_content: null,
        copy_protected: false,
        duration_minutes: 30,
        sort_order: 1,
        is_active: true,
      },
      {
        id: "lesson-1-2",
        course_id: "course-1",
        created_at: "2025-01-01T00:00:00Z",
        updated_at: "2025-01-01T00:00:00Z",
        title: "各ファームの出題傾向",
        description: "BCG、マッキンゼー、ベインなど主要ファームの特徴を比較します。",
        lesson_type: "テキスト",
        content_url: null,
        video_url: null,
        markdown_content: "<h2>主要戦略ファームの出題傾向</h2><p>各ファームには独自の面接スタイルがあります...</p>",
        copy_protected: true,
        duration_minutes: 20,
        sort_order: 2,
        is_active: true,
      },
    ],
  },
  {
    id: "mod-2",
    course_id: "course-1",
    title: "第2章: フレームワーク思考",
    sort_order: 2,
    lessons: [
      {
        id: "lesson-2-1",
        course_id: "course-1",
        created_at: "2025-01-01T00:00:00Z",
        updated_at: "2025-01-01T00:00:00Z",
        title: "MECE と Issue Tree",
        description: "問題を構造化するための基本ツールを学びます。",
        lesson_type: "動画",
        content_url: null,
        video_url: null,
        markdown_content: null,
        copy_protected: false,
        duration_minutes: 45,
        sort_order: 1,
        is_active: true,
      },
      {
        id: "lesson-2-2",
        course_id: "course-1",
        created_at: "2025-01-01T00:00:00Z",
        updated_at: "2025-01-01T00:00:00Z",
        title: "フレームワーク演習問題",
        description: "実際のケースを使ってフレームワークを適用する練習です。",
        lesson_type: "ケース演習",
        content_url: null,
        video_url: null,
        markdown_content: null,
        copy_protected: false,
        duration_minutes: 60,
        sort_order: 2,
        is_active: true,
      },
    ],
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: "enroll-1",
    user_id: "mock-student",
    course_id: "course-1",
    status: "active",
    enrolled_at: "2025-02-01T00:00:00Z",
    deadline: "2025-04-01T00:00:00Z",
    schedule_status: "on_track",
  },
  {
    id: "enroll-2",
    user_id: "mock-student",
    course_id: "course-3",
    status: "active",
    enrolled_at: "2025-02-15T00:00:00Z",
    deadline: "2025-04-15T00:00:00Z",
    schedule_status: "slightly_behind",
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    title: "3月のメンタリングスケジュール更新",
    content: "3月のメンタリングスケジュールが更新されました。各自のダッシュボードからご確認ください。予約枠に限りがありますので、お早めにご予約をお願いします。",
    priority: "normal",
    published_at: "2025-02-25T10:00:00Z",
    author_id: "admin-1",
  },
  {
    id: "ann-2",
    title: "新コース「戦略思考フレームワーク」リリース",
    content: "お待たせしました！新コース「戦略思考フレームワーク」がリリースされました。MECE、仮説思考、Issue Treeなど、実践的なフレームワークを12週間で習得できます。",
    priority: "high",
    published_at: "2025-02-20T09:00:00Z",
    author_id: "admin-1",
  },
  {
    id: "ann-3",
    title: "システムメンテナンスのお知らせ",
    content: "2月28日 深夜2:00〜4:00にシステムメンテナンスを実施します。この間、一部機能がご利用いただけません。ご迷惑をおかけしますが、ご了承ください。",
    priority: "urgent",
    published_at: "2025-02-18T14:00:00Z",
    author_id: "admin-1",
  },
];

export const mockApplications: EnrollmentApplication[] = [
  {
    id: "app-1",
    name: "田中 太郎",
    email: "tanaka@example.com",
    phone: "090-1234-5678",
    motivation: "BCGへの転職を目指しています。ケース面接の対策を体系的に行いたいと考えています。",
    experience: "総合商社3年目。M&A関連業務に従事。",
    course_id: "course-1",
    status: "pending",
    created_at: "2025-02-26T10:00:00Z",
  },
  {
    id: "app-2",
    name: "佐藤 花子",
    email: "sato@example.com",
    phone: "080-9876-5432",
    motivation: "マッキンゼーに興味があり、戦略思考を鍛えたいです。",
    experience: "外資系メーカー マーケティング部門 2年。",
    course_id: "course-4",
    status: "approved",
    created_at: "2025-02-20T08:00:00Z",
    reviewed_at: "2025-02-21T10:00:00Z",
  },
];

export const mockProgressSheets: ProgressSheet[] = [
  {
    id: "ps-1",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2024/12/16",
    session_number: 1,
    problem_solved: "東京タワーの年間来場者数＋売上向上",
    level_fermi: "上級者レベル：短時間かつノーミスで（式・根拠・計算）できる",
    level_case: "初級者レベル：施策がアイデアベース、課題から考えられていない、構造化やロジックが甘い",
    level_mck: null,
    good_points: "・供給ベースから算出できておりよかったです\n・設定した数値・根拠ともに違和感はなかったです\n・ディスカッションで議論を進める意識がみられてよかったです",
    improvement_points: "・課題と施策のつながりが薄い印象です。課題の深堀りをすることを意識するとよいです。",
  },
  {
    id: "ps-2",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2024/12/16",
    session_number: 2,
    problem_solved: "大学受験予備校・塾の市場規模推定＋株式会社ナガセの成長戦略",
    level_fermi: "中級者レベル：基本動作を習得しているが、式・根拠・計算で小さなミスや指摘を受ける",
    level_case: "初級者レベル：施策がアイデアベース、課題から考えられていない、構造化やロジックが甘い",
    level_mck: null,
    good_points: "・基本的な立式は問題なかったと思います\n・セグメンテーションも納得感がありました\n・ディスカッションでこちらの意見を踏まえてアップデートする意識がみられてよかったです",
    improvement_points: "・結論・因数・数字・根拠の順番に発表すると聞きやすいものになると思います\n・抽象的な課題がでてきたら、具体的にはどういうことか？を考えるとよいと思います",
  },
  {
    id: "ps-3",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2024/12/18",
    session_number: 3,
    problem_solved: "ドイツの自動車保険会社の支払い手当額の減少",
    level_fermi: null,
    level_case: null,
    level_mck: "中級者レベル：一応MECEではあるものの、事前に覚えた型に当てはめるにとどまっている",
    good_points: "・基本的な要素は網羅的に挙げられておりよかったです\n・保険適用率もファーストアウトプットで出せておりよかったです",
    improvement_points: "・お題特有の要素を出す意識を持つとよりよかったと思います\n・図表読み取りはファクトだけでなく、そこから何が言えるかを考えるとよいです",
  },
  {
    id: "ps-4",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2024/12/25",
    session_number: 4,
    problem_solved: "マッチングアプリの市場規模＋売上向上",
    level_fermi: "上級者レベル：短時間かつノーミスで（式・根拠・計算）できる",
    level_case: "中級者レベル：課題から考える・構造化して発表・深い分析をする姿勢があるが、ミスや指摘を受ける",
    level_mck: null,
    good_points: "・需要ベースから算出できており、因数も過不足なかったかと思います\n・数値設定についても納得感がありました\n・施策の方向性自体は一定筋がよかったかと思います",
    improvement_points: "・課題と施策のつながりを意識するとよいです\n・課題の深堀りが足りないことにより、アイデアベース感があります",
  },
  {
    id: "ps-5",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2024/12/27",
    session_number: 5,
    problem_solved: "オンライン診療の市場規模＋普及させるには",
    level_fermi: "上級者レベル：短時間かつノーミスで（式・根拠・計算）できる",
    level_case: "中級者レベル：課題から考える・構造化して発表・深い分析をする姿勢があるが、ミスや指摘を受ける",
    level_mck: null,
    good_points: "・セグメンテーションが意味のある切り方になっていました\n・そのほかの切り方についても、ディスカッションで出てきておりよかったです",
    improvement_points: "・どのようなターゲットと親和性があるのかをより検討できるとよかったです\n・年齢や時間の有無だけでなく、病院に行く目的なども出せるとよかったです",
  },
  {
    id: "ps-6",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2024/12/30",
    session_number: 6,
    problem_solved: "タクシー会社の売上推定＋タクシー広告の魅力の網羅構造",
    level_fermi: "上級者レベル：短時間かつノーミスで（式・根拠・計算）できる",
    level_case: "中級者レベル：課題から考える・構造化して発表・深い分析をする姿勢があるが、ミスや指摘を受ける",
    level_mck: null,
    good_points: "・供給ベース算出できており、数値の置き方についても問題なかったです。また、妥当性の検証についても問題なくできておりよかったです\n・タクシー広告の魅力を幅広に出せておりよかったです\n・ディスカッションで質問の意図をくみ取ろうとする意識がありよかったです",
    improvement_points: "・網羅構造の際に、具体から考えること自体はよいですが、抽象化する意識を持つと全体の構造が整理しやすく、抜け漏れがなくなると思います",
  },
  {
    id: "ps-7",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2025/01/11",
    session_number: 7,
    problem_solved: "オンライン大学",
    level_fermi: null,
    level_case: null,
    level_mck: "上級者レベル：問題に応じて最適な構造化を行うことができている",
    good_points: "・前提を懐疑して考えられていたこと\n・計算問題で効率化の視点を持ってただ脳死で計算するだけに留まっていなかった点",
    improvement_points: "・大学の存在意義、目的が営利活動だけではなく学問機関としての役割を持っていることを踏まえれていなかった（ディスカッションでは気づくことができていたのでOK）",
  },
  {
    id: "ps-8",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2025/01/11",
    session_number: 8,
    problem_solved: "歌舞伎町のゴミ問題",
    level_fermi: null,
    level_case: null,
    level_mck: null,
    good_points: "・構造化による網羅性の担保を意識できていた\n・筋の良い仮説を創出できていた",
    improvement_points: "・ポイ捨て問題を、具体的にどのようなゴミなのかまで想像する\n・ポイ捨て問題＝軽犯罪、と抽象化することで、網羅性を担保する\n・罰則を、物理的な罰則だけでなく、罪悪感や白い目で見られる等の心理的罰則まで含めて考える",
  },
  {
    id: "ps-9",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2025/01/13",
    session_number: 9,
    problem_solved: "新しい税金を考えよ",
    level_fermi: null,
    level_case: "上級者レベル：深い分析に基づいて仮説を創出しロジカルに発表することができる",
    level_mck: null,
    good_points: "・問題の趣旨を面接官に聞くことで正確に把握できていたこと\n・「新しさ」を表面的な側面ではなく、抜本的・構造的な側面から提案できていたこと",
    improvement_points: "・構造化することで、アイデアベースで出てきた1つのアイデアを起点に、思考を深めていく技術使えるようになるとより思考が体系化、網羅化されます。",
  },
  {
    id: "ps-10",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2025/01/17",
    session_number: 10,
    problem_solved: "新聞の市場規模＋朝日新聞の成長戦略",
    level_fermi: "内定者レベル：発展的なお題も落ち着いて思考を深め妥当な答えを出すことができる",
    level_case: "中級者レベル：課題から考える・構造化して発表・深い分析をする姿勢があるが、ミスや指摘を受ける",
    level_mck: null,
    good_points: "【フェルミ】\n・特に問題なし\n【ケース】\n・衰退期という商材特性を踏まえ新規事業を検討できていた\n・既存のアセットを踏まえ妥当性の高い新記事業を創出することができていた",
    improvement_points: "【ケース】\n・新聞事業をどのように改革していくか、V字回復していくかという真正面の議論ができていなかった。新聞というはあくまで暫定的な価値創出のための手段であり、顧客が真に求めているニーズは時代と共に一定変容はしたとしても、残っているはずであるため、「新聞」という形にとらわれずに事業拡大していく方向性を探ってほしい\n・新規事業がインパクトが小さく感じられた",
  },
  {
    id: "ps-11",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2025/01/21",
    session_number: 1,
    problem_solved: "アメリカのおもちゃメーカー",
    level_fermi: null,
    level_case: null,
    level_mck: "上級者レベル：問題に応じて最適な構造化を行うことができている",
    good_points: "【論点設計】\n・重要な論点が網羅できていた\n・重要な方向性の仮説が出せていた\n【図表】\n・しっかりファクトを洗い出した上で、示唆も網羅的に読み取ろうという姿勢があった",
    improvement_points: "【論点設計】\n・買収の場合は、その企業にこだわる理由がないことが固有の特徴のため、なぜA社か？という論点を組み込む\n・マジョリティでの買収の場合、買収後のV字回復を自ら担う必要があるため、具体的な成長戦略の検討ができると加点を狙える\n【図表】\n・1番読みって欲しいメッセージが各図表にはある場合が多いため、メインのメッセージを素直に読みってあげる",
  },
  {
    id: "ps-12",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2025/01/21",
    session_number: 12,
    problem_solved: "iphoneの世界販売台数、10年後の価格予測",
    level_fermi: "上級者レベル：短時間かつノーミスで（式・根拠・計算）できる",
    level_case: "上級者レベル：深い分析に基づいて仮説を創出しロジカルに発表することができる",
    level_mck: null,
    good_points: "【フェルミ】\n・立式が概ね正しく計算までスマートにできていた\n【ケース】\n・多角的にプライシングについて考えることができた\n・誘導に乗ることができた",
    improvement_points: "【フェルミ】\n・平均所有個数は1であっても式に入れておくべきです\n・世界全体の話をしているが、日本固有の事情に引っ張られていた\n【ケース】\n・戦略からの視点、売上最大化の視点でプライシングを考える",
  },
  {
    id: "ps-13",
    student_id: "mock-student",
    mentor_id: "mentor-1",
    session_date: "2025/02/24",
    session_number: 13,
    problem_solved: "漁師の数推定、漁業会社の売上向上施策を網羅的にあげる",
    level_fermi: "中級者レベル：基本動作を習得しているが、式・根拠・計算で小さなミスや指摘を受ける",
    level_case: "中級者レベル：課題から考える・構造化して発表・深い分析をする姿勢があるが、ミスや指摘を受ける",
    level_mck: null,
    good_points: "【フェルミ】\n・多角的に式を検討できた\n・気付きにくい箇所（輸出入の考慮）が考慮できていた\n【ケース】\n・構造化して考えることができていた",
    improvement_points: "【フェルミ】\n・分母と分子の定義が異なってしまい（売上/利益、小売価格/生産者への還元価格）計算に誤謬が生じた\n【ケース】\n・因数分解が実態と乖離したものになった（なるべく絵を思い浮かべる）\n・既存の収益ドライバーだけでなく、新規収益源も探る",
  },
];
